#!/bin/bash

sudo yum install httpd -y
sudo systemctl status httpd
sudo systemctl start httpd
sudo systemctl enable httpd
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --reload

 cd /var/www/html
 touch index.html
 vi index.html
 <h1>This is my first personal website</h1>
